FROM node:16-buster AS development

RUN apt-get update && apt-get install -y musl-dev

RUN ln -s /usr/lib/x86_64-linux-musl/libc.so /lib/libc.musl-x86_64.so.1

WORKDIR /app

COPY package*.json ./

RUN yarn install

COPY . .